export default {
    categories: [],
    aspnetusers:[],
    loggedIn: false,
    username: '',
    products: [],
    product: null,
    tags: [],
    cart:[],
    profile: null,
    address: [],
    orders:[],
    order:null,
    status:'',
    sales: [],
    sale: null,
    recevieddate: null,
    importproduct:[],
    feedbacks:[],
}